spring.application.name=JewelleryService

#db configuration
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=system
spring.datasource.password=oracle
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
